server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/ai_insight
    username: aiuser
    password: aipassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

openai:
  default-model: gpt-3.5-turbo
  available-models:
    - gpt-3.5-turbo
    - gpt-4
  model-pricing:
    gpt-3.5-turbo: 1
    gpt-4: 5

billing:
  model: credits
  free-tier-limit:
    summarize: 3
    chat: 0

features:
  enable-chat: true
  enable-summary: true
  enable-gpt4-selection: true
